#Frontend unit tests and linting
name: frontendTest

on: [pull_request,push]

jobs:
  Set_up:
    name: setup react
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: yarn
        run: npm install -g yarn

      - name: creating yarn.lock
        run: yarn install

      - name: installing eslint
        run: yarn add -g eslint

      - name: react_linting test
        run: eslint '**/*.{js,jsx,ts,tsx}'

      - name: run test
        run: yarn test

      

  
