#Frontend unit tests and linting
name: frontendTest

on: [pull_request,push]

jobs:
  react_linting_test:
    name: react_linting test
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - run: eslint '**/*.{js,jsx,ts,tsx}'

  run_Jest_test:
    name: run jest test
    runs-on: ubuntu-latest
    steps:
      - uses: ./
      - name: run test
        run: yarn test

  
